[project]
name = "wardrobe-api"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Oussama Fourati", email = "fourati.oussama9@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "fastapi[standard]>=0.141.1",
    "psycopg[binary]>=3.3.6",
    "pydantic-settings>=2.15.0",
    "sqlalchemy>=2.1.1",
]

[project.scripts]
wardrobe-api = "wardrobe_api:main"

[build-system]
requires = ["uv_build>=0.12.20,<0.13.0"]
build-backend = "uv_build"
